#!/usr/bin/env python3
"""gen_scenes.py — build the probe's stored camera scenes.

Emits app/scenes.c: SCENE_COUNT raw 64x64 8-bit grayscale images placed in
the ROM **detector image store**, a fixed-address region OUTSIDE the golden
application image. The player's binary therefore contains no pixels — only
the code that reads them. See spec §6.4a.

Two scenes are imported from NASA planetary imagery in assets/; the survey
star field and the Mimas easter egg are rendered procedurally here.
Everything is deterministic, so every build is byte-identical and scenario
assertions stay stable.
"""
import math
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from png import read_gray_png                                   # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
W = H = 64
N = W * H


class R:
    """Deterministic LCG — reproducible across Python versions."""
    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFF

    def next(self):
        self.s = (1103515245 * self.s + 12345) & 0x7FFFFFFF
        return self.s

    def rng(self, lo, hi):
        return lo + self.next() % (hi - lo + 1)


def add(img, x, y, v):
    if 0 <= x < W and 0 <= y < H:
        p = img[y * W + x] + v
        img[y * W + x] = 255 if p > 255 else p


def star(img, cx, cy, peak, spread=1.0):
    r = int(spread * 2) + 1
    for dy in range(-r, r + 1):
        for dx in range(-r, r + 1):
            v = int(peak * math.exp(-(dx * dx + dy * dy) / (2.0 * spread * spread)))
            if v:
                add(img, cx + dx, cy + dy, v)


def imported(name):
    """Load a NASA source image from assets/, resampled to 64x64."""
    path = ASSETS / name
    w, h, px = read_gray_png(path)
    if (w, h) == (W, H):
        return list(px)
    out = [0] * N                                   # nearest-neighbour
    for y in range(H):
        sy = y * h // H
        for x in range(W):
            out[y * W + x] = px[sy * w + (x * w // W)]
    return out


# ---- scene 0: survey field K-25 — a plain star field -----------------
def scene_survey():
    r = R(0x5A17)
    img = [0] * N
    for y in range(H):                              # faint sky gradient
        v = 7 + 7 * y // H
        for x in range(W):
            img[y * W + x] = v
    for _ in range(38):
        star(img, r.rng(1, W - 2), r.rng(1, H - 2), r.rng(150, 245), 0.85)
    for _ in range(60):
        star(img, r.rng(0, W - 1), r.rng(0, H - 1), r.rng(40, 90), 0.6)
    return img


# ---- scene 3: Mimas — the "Death Star moon" easter egg ---------------
# Saturn's moon Mimas, whose 130 km Herschel crater famously gives it a
# Death Star silhouette. Rendered here rather than imported so the joke
# carries no third-party artwork.
def scene_mimas():
    r = R(0x4D1A)
    img = [0] * N
    for _ in range(45):                             # background stars
        star(img, r.rng(0, W - 1), r.rng(0, H - 1), r.rng(60, 200), 0.55)

    cx, cy, rad = 30.0, 33.0, 23.0
    hx, hy, hrad = 22.0, 24.0, 8.0                  # Herschel crater
    craters = [(r.rng(-18, 18), r.rng(-18, 18), r.rng(2, 5)) for _ in range(22)]

    for y in range(H):
        for x in range(W):
            dx, dy = x - cx, y - cy
            d = math.hypot(dx, dy)
            if d > rad:
                continue
            # Lit from the upper left; crescent terminator toward lower right.
            nx, ny = dx / rad, dy / rad
            nz = math.sqrt(max(0.0, 1.0 - nx * nx - ny * ny))
            lam = (-0.62 * nx) + (-0.45 * ny) + (0.64 * nz)
            v = 22 + 210 * max(0.0, lam) ** 0.85

            for (ox, oy, orad) in craters:          # pocked surface
                cd = math.hypot(dx - ox, dy - oy)
                if cd < orad:
                    v *= 0.72
                elif cd < orad + 1.0:
                    v *= 1.12

            hd = math.hypot(dx - (hx - cx), dy - (hy - cy))
            if hd < hrad:                            # Herschel: deep bowl
                depth = math.sqrt(max(0.0, 1.0 - (hd / hrad) ** 2))
                v *= (0.30 + 0.22 * (1.0 - depth))
                if hd < hrad * 0.26:                 # central peak
                    v *= 2.5
            elif hd < hrad + 1.6:                    # bright rim
                v *= 1.5

            img[y * W + x] = max(0, min(255, int(v)))
    return img


SCENES = [
    ("survey field K-25 (procedural star field)", scene_survey),
    ("1 Ceres — Occator bright spots (NASA/JPL Dawn)",
     lambda: imported("ceres.png")),
    ("Saturn north polar vortex (NASA/JPL Cassini)",
     lambda: imported("saturn_hexagon.png")),
    ("Mimas — easter egg, reachable only by the 1% roll", scene_mimas),
]


def main():
    out = ROOT / "app" / "scenes.c"
    lines = [
        "/* scenes.c — GENERATED by tools/gen_scenes.py. Do not edit by hand.",
        " *",
        " * The probe's detector image store: raw 64x64 8-bit grayscale source",
        " * pixels. This object is linked into the ROM image at a fixed address",
        " * OUTSIDE the golden application image, so the binary the player",
        " * analyses contains no imagery — only the code that reads it. The",
        " * camera writes its processed output into the frame buffer, and that",
        " * captured raw is what the ground downlinks. (Spec §6.4a.)",
        " */",
        '#include "probe.h"',
        "",
        "__attribute__((section(\".scene_store\"), used))",
        "const uint8_t scene_store[SCENE_COUNT][SCENE_PIXELS] = {",
    ]
    for idx, (name, fn) in enumerate(SCENES):
        img = fn()
        assert len(img) == N and all(0 <= v <= 255 for v in img), name
        lines.append(f"/* scene {idx}: {name} */")
        lines.append("{")
        for r0 in range(0, N, 16):
            lines.append("    " + ",".join(f"0x{v:02X}" for v in img[r0:r0 + 16]) + ",")
        lines.append("},")
    lines.append("};")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"{out}: {len(SCENES)} scenes x {N} bytes "
          f"-> ROM store {len(SCENES) * N} bytes")


if __name__ == "__main__":
    main()
